### ISSUE TITLE
FOW Release VI changed firemode inheritance for many weapons.

### ISSUE THREAD

**Issue by Drofseh** [Anrop/Faces-Of-War-JSRS#2]
Just want to make you aware as this will probably require a review and update.
An example would be the `fow_w_m1a1_thompson` which now has a `class Burst_AI : Mode_Burst` firemode that it did not have before.

**Comment by Drofseh** [comment]
@Dahlgren

**Comment by Dahlgren** [comment]
Thanks for reaching out! I've updated the changed class inheritances and added `Burst_AI` for those existing weapons I could find it on.
